### ISSUE TITLE
Implement Search/Filter Graph

### ISSUE THREAD

**Issue by anapoparic** [anapoparic/DataGraphVisualization#12]
**Description:**
implement a method that will search or filter the graph by the entered query

- [x]  Implement a method that will call a search or filter depending on the entered query
- [x]  Implement search method
- [x]  Implement filter method

Acceptance Criteria:

- The Graph class is implemented with methods for adding nodes and edges.
- A regex was used to parse the entered query
- It is possible to search by several types of data

**Comment by VesnaVasic** [comment]
Great job!
